quarkus:
  http:
    port: 8888
    cors: true
  application:
    name: demo
  live-reload:
    instrumentation: true
  datasource:
    db-kind: mysql
    username: root
    password: root
    jdbc:
      url: jdbc:mysql://localhost:3306/example_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      driver: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    meta-object-handler: com.example.handler.MetaHandler